### ISSUE TITLE
Noticed a few issues in sigdigits.py

### ISSUE THREAD

**Issue by PurplePachyderm** [verificarlo/significantdigits#15]
Hi, I'm @pablooliveira 's intern and I'm currently working at the LI-PaRAD. 

I was looking into significantdigits to integrate it in my project, and ran into a few issues with `sigdigits.py` (all of which I could solve quite easily with small changes to the code) : 

- https://github.com/verificarlo/significantdigits/blob/1f8effb0f2b2a1e9dc10c7cf4ba87cc559d0c1b0/sigdigits.py#L56-L59
First of all, I'm guessing the minus sign on line 57 should not be there ? The function would  just return the result with the wrong sign here.
Moreover, it looks like `frompyfunc`  now requires two other arguments (`nin` and `nout`) to specify the number of input/output arguments of the resulting function (https://numpy.org/doc/stable/reference/generated/numpy.frompyfunc.html). I assume they were previously optional with a default value of 1, and were made mandatory in a recent update.

- https://github.com/verificarlo/significantdigits/blob/1f8effb0f2b2a1e9dc10c7cf4ba87cc559d0c1b0/sigdigits.py#L99-L102
I think `x` and `y` should be used here, instead of `array` and `reference` (since they are previously used to generate `x` and `y`). For instance, if `reference` is `None`, this would result in an error.

- https://github.com/verificarlo/significantdigits/blob/1f8effb0f2b2a1e9dc10c7cf4ba87cc559d0c1b0/sigdigits.py#L146
Here the `axis` argument is not recognized, nor is it referenced in NumPy's documentation (https://numpy.org/doc/stable/reference/maskedarray.baseclass.html#the-maskedarray-class). Once again, this probably has something to do with it being removed in an update.

As I previously wrote, these errors were easy to fix with only minor changes to the code: if you're interested, I can open a PR with my fixes. I would also be pleased to discuss these errors if you want to. 

Thanks for your attention,
Aurélien Delval

**Comment by yohanchatelain** [comment]
Hi @PurplePachyderm, thank you for your comments! Indeed, I made a fix for the two first points you've mentioned but I didn't push it. I didn't catch the last one but thanks for pointing out! I will push the fix and you could open a PR for the last one, adding your contribution to the project.

**Comment by PurplePachyderm** [comment]
Sounds good! I'll open my PR after your push then.
